### ISSUE TITLE
do you have got the same coupling and directivity results with the IEEE artical?

### ISSUE THREAD

**Issue by kleeneee** [ckflight/RF_DIRECTIONAL_BRIDGE#1]
Thanks for the sharing. I have learnt a lot about it. However, do you have got the same coupling and directivity results with the IEEE artical?

**Comment by ckflight** [comment]
In the case of dB measurement with power meter yes I had similar and good results. But I did not have VNA at that time to test it. However the exact coupling results might vary because of the toroid and cable used for creating the transformer and soldering the passive components at the SMA side. Therefore you should test it for yourself. Someone made this coupler and measured it with a VNA. I will put them on the ReadMe. Check it as well.

**Comment by kleeneee** [comment]
Thank you very much! I will make and test it.

**Comment by ckflight** [comment]
You are welcome. Once you test it with a VNA, add results to this project as well for others to benefit.

**Comment by kleeneee** [comment]
OK. But now I do not know how to improve directivity. And I  want to have very very high directivity.

**Comment by ckflight** [comment]
This is a specific design and i do not know how to improve it on this design. You should ask this question on Stack Exchange.

**Comment by kleeneee** [comment]
OK! Thank you very much!
